//login action types

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const PATIENT_LOGIN = "PATIENT_LOGIN";
export const LOG_OUT = "LOG_OUT";

export const ADD_PATIENT_DETAILS = "ADD_PATIENT_DETAILS";

export const FETCH_PATIENTS_BEGIN = "FETCH_PATIENTS_BEGIN";
export const FETCH_PATIENTS_SUCCESS = "FETCH_PATIENTS_SUCCESS";
export const FETCH_PATIENTS_FAILURE = "FETCH_PATIENTS_FAILURE";

export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";

export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
